version: '3.4'

services:
  mysql:
    build:
      context: ./mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_VERSION: ${MYSQL_VERSION}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    networks:
      - default
  geneiouslm:
    ports:
      - "27001:27001"
      - "49630:49630"
    tty: true
    build:
      context: ./geneiouslm
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
  postgres:
    shm_size: 256M
    build:
      context: ./postgres
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres/conf.d:/conf.d
    environment:
      - POSTGRES_VERSION=${POSTGRES_VERSION}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REPLICATION_USER=${REPLICATION_USER}
      - REPLICATION_PASSWORD=${REPLICATION_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    networks:
      - default

networks:
  default:

volumes:
  pglog:
  pgdata:
