version: '3.4'

services:
  mysql:
    build:
      context: ./mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_VERSION: ${MYSQL_VERSION}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - default
  geneiouslm:
    build:
      context: ./geneiouslm
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}

networks:
  default:
